spring:
  datasource:
    url: jdbc:h2:mem:looknshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
  profiles:
    include: oauth

jwt:
  secretKey: secretKey1234
  access:
    header: Authorization
    expiration: 3600000 # 1시간 1000 * 60 * 60
  refresh:
    header: Authorization-refresh
    expiration: 1209600000 # 14일 1000 * 60 * 60 * 24 * 14

oauth:
  authorizedRedirectUri: http://localhost:3000/oauth2/redirect

logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**